### ISSUE TITLE
Pokemon Ultra Moon & ultra sun

### ISSUE THREAD

**Issue by MyBroAndMe** [PretendoNetwork/website#276]
Hello i recently found out about pretendo so i installed it but when i tried it on an pokemon game it didnt work so if you could fix this thank you

**Comment by dogmann112** [comment]
This is the wrong place to open an issue at. The implementation of Pokemon (Ultra) Sun & Moon is currently not getting worked on. You can view the progress of all features on here: https://pretendo.network/progress.
Otherwise you can go to the [GitHub Profile of Pretendo](https://github.com/PretendoNetwork) where you can search for any Repository. If you don't find one for your game it simply wasn't worked on yet. 
Bye!

**Comment by ExperiencersInternational** [comment]
Pretendo is in **BETA**!

I'd recommend going to their Discord server if you have an account or contacting a developer directly about game support.

**Comment by jonbarrow** [comment]
Not the right repo, and as others have said the project is in beta. Support for games will come when we get to them
