### ISSUE TITLE
[Enhancement]: Add citra guide

### ISSUE THREAD

**Issue by erew70** [PretendoNetwork/website#333]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What enhancement would you like to see?

I have a fork of this repository ready to merge but i need to ask for approval here. Also how would i test the changes? I have no clue how to self host the website. Thank you!

### Any other details to share? (OPTIONAL)

The fork has been updated to add a citra guide, check out the [fork](https://github.com/erew70/website/tree/dev)

If you would like you can tweak the citra.md file a little bit. I also added info on what LLE modules need to be enabled for netpass

**Comment by jonbarrow** [comment]
I have checked your fork, and it has several issues. For starters, please familiarize yourself with our [contributing guide](https://github.com/PretendoNetwork/.github/blob/master/.github/CONTRIBUTING.md). This goes over everything you need to know about contributing to our codebases, and your fork violates several points.

The first one being that work should only really be done *after* the issue is approved. Otherwise we run into cases where people are making changes we are not interested in . That's the whole point of the approved issues system. That was done backwards in this case (work was done and *then* an issue was made).

Secondly ***all*** of your commit messages are just `Update citra.md`. We have an entire section in our contribution guide about commit messages, because messages like `Update citra.md` are not helpful at all for knowing what your changes actually were.

About this feature request specifically: we are aware that Pablo's fork exists and that it supports online play. That being said, @PabloMK7 has been very wary of making any direct guides on how to use the emulator like this, which is why we've intentionally never updated the Citra guide. We have been specifically asked to NOT make guides like this as it involves mentioning console-unique files/keys, which was a large part of the Yuzu lawsuit.

Until we get direct word from Pablo, or other 3DS emulator maintainers like Mikage, Panda3DS, etc. (if they support online) about how they want guides to be structured, and we can figure out a safe way to do so without bringing any legal attention to ourselves, we have no intentions of having a Citra/3DS emulator guide. And if we do, those changes will almost certainly be handled internally to make sure everything is up to snuff.

(This is why the approved issues system exists, to get approval for features before working on them)
